---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	analyze_and_route_query(analyze_and_route_query)
	ask_for_more_info(ask_for_more_info)
	respond_to_general_query(respond_to_general_query)
	propose_action(propose_action)
	human_approval_node(human_approval_node)
	execute_action(execute_action)
	memory_node(memory_node)
	__end__([<p>__end__</p>]):::last
	__start__ --> analyze_and_route_query;
	address_book_agent_respond --> memory_node;
	analyze_and_route_query --> propose_action;
	conduct_travel_search_get_map_result --> memory_node;
	conduct_web_search_get_search_result --> memory_node;
	execute_action -.-> address_book_agent___start__;
	execute_action -.-> ask_for_more_info;
	execute_action -.-> conduct_travel_search___start__;
	execute_action -.-> conduct_web_search___start__;
	execute_action -.-> file_agent_read_file;
	execute_action -.-> researcher_agent_create_research_plan;
	execute_action -.-> respond_to_general_query;
	execute_action -.-> retrieval_agent_generate_query;
	file_agent_llm_call --> memory_node;
	human_approval_node -.-> execute_action;
	propose_action --> human_approval_node;
	researcher_agent_respond --> memory_node;
	retrieval_agent_respond --> memory_node;
	ask_for_more_info --> __end__;
	memory_node --> __end__;
	respond_to_general_query --> __end__;
	subgraph conduct_web_search
	conduct_web_search___start__(<p>__start__</p>)
	conduct_web_search_llm_call(llm_call)
	conduct_web_search_tool_node(tool_node)
	conduct_web_search_get_search_result(get_search_result)
	conduct_web_search___start__ --> conduct_web_search_llm_call;
	conduct_web_search_llm_call -.-> conduct_web_search_get_search_result;
	conduct_web_search_llm_call -.-> conduct_web_search_tool_node;
	conduct_web_search_tool_node --> conduct_web_search_llm_call;
	end
	subgraph conduct_travel_search
	conduct_travel_search___start__(<p>__start__</p>)
	conduct_travel_search_llm_call(llm_call)
	conduct_travel_search_tool_node(tool_node)
	conduct_travel_search_get_map_result(get_map_result)
	conduct_travel_search___start__ --> conduct_travel_search_llm_call;
	conduct_travel_search_llm_call -.-> conduct_travel_search_get_map_result;
	conduct_travel_search_llm_call -.-> conduct_travel_search_tool_node;
	conduct_travel_search_tool_node --> conduct_travel_search_llm_call;
	end
	subgraph retrieval_agent
	retrieval_agent_generate_query(generate_query)
	retrieval_agent_retrieve(retrieve)
	retrieval_agent_respond(respond)
	retrieval_agent_generate_query --> retrieval_agent_retrieve;
	retrieval_agent_retrieve --> retrieval_agent_respond;
	end
	subgraph researcher_agent
	researcher_agent_create_research_plan(create_research_plan)
	researcher_agent_respond(respond)
	researcher_agent_conduct_research_retrieve_documents -.-> researcher_agent_respond;
	researcher_agent_create_research_plan --> researcher_agent_conduct_research_generate_queries;
	subgraph conduct_research
	researcher_agent_conduct_research_generate_queries(generate_queries)
	researcher_agent_conduct_research_retrieve_documents(retrieve_documents)
	researcher_agent_conduct_research_retrieve_documents -.-> researcher_agent_conduct_research_generate_queries;
	researcher_agent_conduct_research_generate_queries -.-> researcher_agent_conduct_research_retrieve_documents;
	end
	end
	subgraph file_agent
	file_agent_read_file(read_file)
	file_agent_llm_call(llm_call)
	file_agent_read_file --> file_agent_llm_call;
	end
	subgraph address_book_agent
	address_book_agent___start__(<p>__start__</p>)
	address_book_agent_generate_query(generate_query)
	address_book_agent_retrieve(retrieve)
	address_book_agent_think(think)
	address_book_agent_respond(respond)
	address_book_agent___start__ --> address_book_agent_generate_query;
	address_book_agent_generate_query --> address_book_agent_retrieve;
	address_book_agent_retrieve --> address_book_agent_think;
	address_book_agent_think -.-> address_book_agent_generate_query;
	address_book_agent_think -.-> address_book_agent_respond;
	end
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
